feat: lazy load jsonParser and yamlParser FlagFileParser
launchdarkly/java-core pull request #35
Opened 2024-05-29 09:25 UTC by jtjeferreira

I want to be able to use the thin jar without the snakeyaml dependency, since I don't need to parse yaml files, just json files.

If I try that I get the following exception:

```
Cause: java.lang.ClassNotFoundException: org.yaml.snakeyaml.error.YAMLException
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:103)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
at com.launchdarkly.sdk.server.integrations.FileDataSourceParsing$FlagFileParser.<clinit>(FileDataSourceParsing.java:76)
at com.launchdarkly.sdk.server.integrations.FileDataSourceImpl$DataLoader.load(FileDataSourceImpl.java:241)
at com.launchdarkly.sdk.server.integrations.FileDataSourceImpl.reload(FileDataSourceImpl.java:108)
at com.launchdarkly.sdk.server.integrations.FileDataSourceImpl.start(FileDataSourceImpl.java:92)
at com.launchdarkly.sdk.server.LDClient.<init>(LDClient.java:239)
```

This PR avoids loading the `YamlFlagFileParser` by using a holder class idiom for lazy initialization of a static field.

**Requirements**

- [ ] I have added test coverage for new or changed functionality
  - Existing tests still pass, but I don't see a way to add unit tests for this functionality. I published this library locally and tested it on my project successfully. 
- [x] I have followed the repository's [pull request submission guidelines](../blob/main/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Related issues**

n/a

**Describe the solution you've provided**

The solution is to lazy load the `YamlFlagFileParser` (and the `JsonFlagFileParser`) so they are only initialised if needed

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

2024-06-04 17:23 UTC, jtjeferreira commented
Hi @tanderson-ld 

First of all, sorry for the late response. 

I think that is an elegant approach, but I think it is a bit over-engineered (it looks like you are proposing a plugin system) for the value of this feature. 

> It should also be impossible at runtime to get to an unsupported parser's code even if another parser is removed from the code 

I think that even with the approach you suggest, we still need to use runtime exceptions for the case when we want to parse YAML, but the yaml parser is not present.

2024-06-11 19:31 UTC, tanderson-ld commented
Hi again @jtjeferreira .  We discussed on team briefly and the consensus was the following:

- A whole plugin scheme is probably overkill
- There should have conditional logic to protect against the ClassNotFound exception instead of relying on Java's static initialization behavior.
- We are fine throwing a dedicated exception if an unsupported file is loaded.

Perhaps the `Class.forName` API could achieve that.  [Stackoverflow with example](https://stackoverflow.com/questions/3466568/check-if-class-exists-in-java-classpath-without-running-its-static-initializer/77473014#77473014)

If you would like to iterate with this feedback we can review again once your changes are pushed.  Alternatively we can file a ticket for a modification.  That would get prioritized according to current work demands and may be some time (likely at least a month).

Let us know your thoughts!  Thank you.

2024-12-12 10:19 UTC, valters requested changes

2024-12-12 10:19 UTC, valters commented on lib/sdk/server/src/main/java/com/launchdarkly/sdk/server/integrations/FileDataSourceParsing.java
> +      static final FlagFileParser INSTANCE = new YamlFlagFileParser();
should be private with a getter so it only gets initialized on access as opposed to having direct reference to variable.

2024-12-20 13:36 UTC, jtjeferreira commented on lib/sdk/server/src/main/java/com/launchdarkly/sdk/server/integrations/FileDataSourceParsing.java
> +      static final FlagFileParser INSTANCE = new YamlFlagFileParser();
you mean something like this?

```suggestion
      private static final FlagFileParser INSTANCE = new YamlFlagFileParser();
      static final FlagFileParser getInstance() {
        return INSTANCE;
      }
```

2024-12-20 13:37 UTC, jtjeferreira commented
@tanderson-ld any updates here?

2025-01-22 16:50 UTC, tanderson-ld approved these changes

2025-01-22 16:51 UTC, merged

2025-01-23 09:57 UTC, jtjeferreira commented
Hi @tanderson-ld. Thanks for merging this PR. Is 7.7.0 on its way? I dont see it yet in maven central.

https://repo1.maven.org/maven2/com/launchdarkly/launchdarkly-java-server-sdk/ shows 7.6.0 as the latest version...